Fix add / edit failure in W2 list form
ustaxes/UsTaxes pull request #536
Opened 2021-09-04 04:32 UTC by zakpatterson

Add grouping functionality to FormListContainer
Adding the rest of lodash made this easier using groupBy

2021-09-04 22:31 UTC, thegrims commented
In MFS, the spouse W2 is under the primary taxpayer's W2, which doesn't seem right
![image](https://user-images.githubusercontent.com/8848557/132109458-093c7008-3f09-4854-ad2f-898f66edcd1d.png)

2021-09-04 22:36 UTC, thegrims requested changes
Spouse W2s showing up under primary taxpayer W2s section

2021-09-05 02:46 UTC, zakpatterson commented
> Spouse W2s showing up under primary taxpayer W2s section

Yea good catch, group titles were messed up, I think it's better now.

2021-09-05 07:29 UTC, thegrims approved these changes

2021-09-05 07:29 UTC, merged