Add react helmet and titles
ustaxes/UsTaxes pull request #548
Opened 2021-09-08 02:52 UTC by bluSCALE4

Update pages so titles are updated on transitions.

2021-09-08 03:06 UTC, thegrims approved these changes

2021-09-09 23:38 UTC, thegrims requested changes
Seeing this error in the unit test
`Invariant failed: You should not use <Prompt> outside a <Router>`

2021-09-11 02:42 UTC, zakpatterson commented on src/components/deductions/F1098eInfo.tsx
> +          <title>1098-E Information | Deductions | UsTaxes.org</title>
Would it be better for all these titles to be in one place in the [Main component](https://github.com/ustaxes/UsTaxes/blob/master/src/components/Main.tsx#L122)

2021-12-09 11:18 UTC, thegrims approved these changes

2021-12-09 11:19 UTC, merged