Remove arbitrary f1040 generator
ustaxes/UsTaxes pull request #561
Opened 2021-09-13 01:19 UTC by zakpatterson

This sounded cool at the time, but if fast-check spots an error, it needs to print out the object that was arbitrarily generated.
The f1040 object has a ton of methods on it, so the output is full of compiled js, leading to confusion. Better to just
have fast-check generate plain objects only.

2021-09-13 05:06 UTC, zakpatterson commented on src/irsForms/Main.ts
> -export const getSchedules = (f1040: F1040, state: Information): Form[] => {
All of this moved to F1040.ts => `makeSchedules`.

2021-09-13 05:10 UTC, zakpatterson commented on src/tests/components/Questions.test.tsx
> -            info.questions.CRYPTO ?? false
f1040 reads this field directly, so this test is not testing anything.

2021-09-14 20:50 UTC, thegrims requested changes
W2 data isn't added to the finished 1040 form

2021-09-15 04:30 UTC, zakpatterson commented
> W2 data isn't added to the finished 1040 form

Good catch, think I fixed this.

2021-09-15 04:39 UTC, thegrims approved these changes

2021-09-15 04:40 UTC, merged